apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:1X3Oi3M=,iv:+W2WwBdPVfB/xoYMCLGw+df52Z/PYoN/OAFim8Djn3s=,tag:RvbRbXlDmQo76pPAMt2P8A==,type:str]
    admin-password: ENC[AES256_GCM,data:tE8Hi1E=,iv:dYGq9Cl5veQaGBPWnrLdHqN55lJzdVZRTM0FgJg9WkY=,tag:VAFbpu2aJ69GGS3akyVPsw==,type:str]
sops:
    age:
        - recipient: age1pclv5mvwasxgcpfrkz9le2f534c5vaff57pw4hthwv9lpkxn5ypqqyhwla
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Wk95T01CWTc3UWJ3YXgx
            Yy9iWktZQ0F2VEVNRW96eGh1T3dzeVVEVURZCnlxMXRaaCtLWUQ0UU13V0V2KzlB
            eFp4cm5JU3lUWGoyRnI1eXIyQUdiRVEKLS0tIG9jcVpqSGx3bnNXZEU2eVZUUzln
            eHpsQmNXMkY5bFlkbWlPNGRjQ2tOWWcKJ2gL5uDnvfRDr6CLZ5QO76DVlvSt2icm
            /2Pp6THlIK2y/xdglvO9zCuioip3BAqrNo0ip/Jd6evFoRac/vUItw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T16:39:06Z"
    mac: ENC[AES256_GCM,data:m6vbMLd6/QEsPwG5b9urqMBLVMQ67V9DOeRiKzHQtuRGC8/meREt3krvIbMewMFXmI7+GrOvREO5M1yo/fgLe1IKROF7UmIjDk6gqeur2M9jYVttyDs7cJWK1sac+sVtOOFesahAnX6x4YiJIbkbg4PMx3MfQIw3S8n/23ikG98=,iv:3jQ5w8UKBaVn5wlM94UFe+U3xG4UVkBI0vSpg5KkN8I=,tag:zayTXJ0EvSJwINctXWYrfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
