apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-k8s-stack
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.78.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: observability
  values:
    vmsingle:
      enabled: true
      spec:
        retentionPeriod: "30"
        storage:
          storageClassName: longhorn
          resources:
            requests:
              storage: 5Gi

    vmagent:
      enabled: true
      spec:
        selectAllByDefault: true
        remoteWrite:
          - url: "http://vmsingle-victoria-k8s-stack-victoria-metrics-k8s-stack.observability.svc:8428/api/v1/write"

    grafana:
      enabled: true
      persistence:
        enabled: true
        type: pvc
        storageClassName: longhorn
        size: 1Gi
      admin:
        existingSecret: grafana-admin-credentials
      additionalDataSources:
        - name: VictoriaLogs
          type: loki
          url: http://victoria-logs-victoria-logs-single-server.observability.svc:9428
        - name: VictoriaTraces
          type: jaeger
          url: http://victoria-traces-vt-single-server.observability.svc:14268

    kube-state-metrics:
      enabled: true
    node-exporter:
      enabled: true

    defaultDashboardsEnabled: true
    defaultRules:
      create: true

    victoria-metrics-operator:
      enabled: true
      controllers:
        scrapeConfig:
          enabled: false

