// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	INTERNALERROR ErrorCode = "INTERNAL_ERROR"
	INVALIDINPUT  ErrorCode = "INVALID_INPUT"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case INTERNALERROR:
		return true
	case INVALIDINPUT:
		return true
	default:
		return false
	}
}

// Defines values for RoutePointTransportType.
const (
	Airplane RoutePointTransportType = "airplane"
	Bus      RoutePointTransportType = "bus"
	Train    RoutePointTransportType = "train"
)

// Valid indicates whether the value is a known member of the RoutePointTransportType enum.
func (e RoutePointTransportType) Valid() bool {
	switch e {
	case Airplane:
		return true
	case Bus:
		return true
	case Train:
		return true
	default:
		return false
	}
}

// Coordinates defines model for Coordinates.
type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// CreateRouteRequest defines model for CreateRouteRequest.
type CreateRouteRequest struct {
	// DurationMaxDays Maximum duration of the trip in days (optional)
	DurationMaxDays *int `json:"durationMaxDays,omitempty"`

	// DurationMinDays Minimum duration of the trip in days
	DurationMinDays int `json:"durationMinDays"`

	// Points List of destination points for the route
	Points []string `json:"points"`

	// StartDate Start date for the trip in YYYY-MM-DD format
	StartDate openapi_types.Date `json:"startDate"`
}

// CreateRouteResponse Result of routes planning
type CreateRouteResponse struct {
	Points []RoutePoint `json:"points"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code ErrorCode `json:"code"`

	// Message Full error message
	Message string `json:"message"`
}

// ErrorCode Error code
type ErrorCode string

// GetCitiesResponse List of cities for the hinting
type GetCitiesResponse struct {
	// Cities List of cities for the route
	Cities *[]string `json:"cities,omitempty"`
}

// RoutePoint defines model for RoutePoint.
type RoutePoint struct {
	// AvailableAmount Amount of available tickets for route segment
	AvailableAmount int64        `json:"availableAmount"`
	Coordinates     *Coordinates `json:"coordinates,omitempty"`

	// Details Additional details about this route point
	Details *string `json:"details,omitempty"`

	// EndTimestamp Unix timestamp for the end of this point in the route
	EndTimestamp int64 `json:"endTimestamp"`

	// Name Name of the route point/destination
	Name string `json:"name"`

	// Price Price for this route segment
	Price float64 `json:"price"`

	// StartTimestamp Unix timestamp for the start of this point in the route
	StartTimestamp int64 `json:"startTimestamp"`

	// TransportType Type of transport for provided route segment
	TransportType RoutePointTransportType `json:"transportType"`
}

// RoutePointTransportType Type of transport for provided route segment
type RoutePointTransportType string

// CreateRouteJSONRequestBody defines body for CreateRoute for application/json ContentType.
type CreateRouteJSONRequestBody = CreateRouteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get cities
	// (GET /v1/cities)
	GetCities(w http.ResponseWriter, r *http.Request)
	// Create a new travel route
	// (POST /v1/routes)
	CreateRoute(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get cities
// (GET /v1/cities)
func (_ Unimplemented) GetCities(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new travel route
// (POST /v1/routes)
func (_ Unimplemented) CreateRoute(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCities operation middleware
func (siw *ServerInterfaceWrapper) GetCities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoute operation middleware
func (siw *ServerInterfaceWrapper) CreateRoute(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/cities", wrapper.GetCities)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/routes", wrapper.CreateRoute)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFfdbts4E30Vgt93sQso8U/TJNBdmnS7BpI0cNMFgsIoaGlsT1ciVXLkxAj87guS+rXkxO0uFntniyPO",
	"mTMzZ0bPPFJppiRIMjx85iZaQSrcz0uldIxSELi/mVYZaEL/LxGElMdgfy+UTgXxkMcqnyfAA06bDHjI",
	"ZZ7OQfNtwBMll4fbbwOu4XuOGmIefmm8HNR+Z9Vbav4NIrJeLjUIgqnKCabwPQdDXeBxrgWhkjfi6Ups",
	"/CMwkcbMPuUhvxFPmOYpKw2ZWjBaASONGUPJYrEx7BflzEXyKw84PIk0S4CHo5OApyjt6zwcBVzmSSJs",
	"hCHpHCrAKAmWnpcKDco9aPx1L6JpQjhrI+h6zBQWqW47ukZD9vIYDNmkW1/eli2Udj61Jbbp7AufqtQ+",
	"uRMaLYxrJWMlbW6QIHVeCgSGNMqlBZCinPjDGp/QWmzsoSGh6UoQdAF+skcsFgQVoJKEh4eHh6Obm6Or",
	"K1bUVgMkHw/HJ0fD0dHoLQ8atSeoUXklvJ3KK8hq4urm7NVKNJmSpieiKZg8caQ7Zg3LEiGlxRHsFG2d",
	"tIrX/2tY8JD/b1D376Bo3oHze2ffsVjaHPdH2BfDe62V7jZQpOKeWJwxc2cBB2nL7wuf3P5xcT25+jq5",
	"vft8zwM+ub1/P729uP76fjr9OG04bVQHGCOWPQ5+y5OEgfNS2ryWvQJNad4X4wegS7SR7c9S2RiRs6tq",
	"b4WS+lLlzQ6+5p/pqZ9NcaNQOnkWa4FOvS5SlXuDdkT+uY2pMmWE0Z9QSIYLjRlYpiBbHTkaNvoQJZ2e",
	"8D6litrz56WCb44qq6pAApOeJFzEMXrdZoUNE3OVE6MVmgKwo6slIL+jIaUxEgkzaPuUFFujQbLaU2Rr",
	"j9TXKQIZ32MKhkSadYF9lvjEqDyvqgNk7AUfjcdlPfaWzehs+PZ0PD4ZHsatFGlPqd+KFMoB0yBj0JgJ",
	"LWKK2DuxZhqjnuvv7OMitoru3vpoRbF/q3Cq/OOsutd+gNfx2en5gbySFtJkStO9O9oFZJ86x6WZw5Rp",
	"tcYY4i4jhY6SFmiZn+dWEARqOyicoNW5KG1elkSX9w5xO9VZJnA3nKCjCV1NsQ5RLlRP791NXLSRHY0o",
	"l5aENSTl7JtvmMkgwsXGnnnNCty4NwETMq42ILsEYgSFVvtC5jzguU54yFdEWTgYJCoSyUoZCs/Pz89d",
	"ZpAcT/d2Z7jU4jEBzS7uJjzga9DGYxwdD4+H1lplIEWGPORvjofHbywlglZOUQbr0aAW+SX0KOMHoEoT",
	"qVB87i71IUxib3RZnuhi+rgrx8Ohn7OSwOuuyLIEI/fq4JuxLp7rzNcjpzM6bpSJ1COf2VZxSvmajnbH",
	"oUto/ySrVb8AsA3424OwHwbG7x89ACaSQFsNN6DXoP1W4Erd5Gkq9KZIQUU8iaWj5xM5HIbPrLFNpC8+",
	"v2KZnkz6Pc4wwSQ8tiqWPSKtipJFiMtduVmpLBNapECgu9lvLIjctygYeqfizY+lvvM1Yz9BOh8VZ/Xa",
	"/8J60di9mzvzwcXT8/W1beuPHY3bv1vtVSTP9ZznV61pbkO0Kr/ZVbbWmCyko+Bjd5bUwr8N9ntyLO51",
	"dToen40brkrO+3x5VNvZz9G9v1udgRddiJnJowiMWeRJ4r63Tv6Nfn0nYlZUODtiKNciwZihzHJqtsh/",
	"ST48uT1t31CTqdeOmXPh7yrLsiWXdhSxGNaQqMwO9sLvayNrVnnavfFjqSSGaUhcXkkVquSnq5JOiFIh",
	"xRKKZaIqd4d6O9v+FQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
