// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	INTERNALERROR ErrorCode = "INTERNAL_ERROR"
	INVALIDINPUT  ErrorCode = "INVALID_INPUT"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case INTERNALERROR:
		return true
	case INVALIDINPUT:
		return true
	default:
		return false
	}
}

// Coordinates defines model for Coordinates.
type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// CreateRouteRequest defines model for CreateRouteRequest.
type CreateRouteRequest struct {
	// DurationMaxDays Maximum duration of the trip in days (optional)
	DurationMaxDays *int `json:"durationMaxDays,omitempty"`

	// DurationMinDays Minimum duration of the trip in days
	DurationMinDays int `json:"durationMinDays"`

	// Points List of destination points for the route
	Points []string `json:"points"`

	// StartDate Start date for the trip in YYYY-MM-DD format
	StartDate openapi_types.Date `json:"startDate"`
}

// CreateRouteResponse Result of routes planning
type CreateRouteResponse struct {
	Points []RoutePoint `json:"points"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code ErrorCode `json:"code"`

	// Message Full error message
	Message string `json:"message"`
}

// ErrorCode Error code
type ErrorCode string

// GetCitiesResponse List of cities for the hinting
type GetCitiesResponse struct {
	// Cities List of cities for the route
	Cities *[]string `json:"cities,omitempty"`
}

// RoutePoint defines model for RoutePoint.
type RoutePoint struct {
	Coordinates *Coordinates `json:"coordinates,omitempty"`

	// Details Additional details about this route point
	Details *string `json:"details,omitempty"`

	// EndTimestamp Unix timestamp for the end of this point in the route
	EndTimestamp int64 `json:"endTimestamp"`

	// Name Name of the route point/destination
	Name string `json:"name"`

	// StartTimestamp Unix timestamp for the start of this point in the route
	StartTimestamp int64 `json:"startTimestamp"`
}

// CreateRouteJSONRequestBody defines body for CreateRoute for application/json ContentType.
type CreateRouteJSONRequestBody = CreateRouteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get cities
	// (GET /v1/cities)
	GetCities(w http.ResponseWriter, r *http.Request)
	// Create a new travel route
	// (POST /v1/routes)
	CreateRoute(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get cities
// (GET /v1/cities)
func (_ Unimplemented) GetCities(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new travel route
// (POST /v1/routes)
func (_ Unimplemented) CreateRoute(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCities operation middleware
func (siw *ServerInterfaceWrapper) GetCities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoute operation middleware
func (siw *ServerInterfaceWrapper) CreateRoute(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/cities", wrapper.GetCities)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/routes", wrapper.CreateRoute)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWbW/jNgz+KwK3DxvgNi/XN/hbr+luAdpekesNKIrgoNpMooMs+SQ6bVDkvw+S7MSJ",
	"nTa9DcO+JRYlPiQfPuQLJDrLtUJFFuIXsMkMM+5/XmhtUqE4of+bG52jIRH+SU6CihTd74k2GSeIIdXF",
	"o0SIgBY5QgyqyB7RwDICqdV0f/tlBAZ/FMJgCvFD7XK09jte3dKP3zEh5+XCICcc6YJwhD8KtNQEnhaG",
	"k9Dqmj8P+CJ8QpsYkbuvEMM1fxZZkbHKkOkJoxkyMiJnQrGULyz7TXtzLn+HCPCZZ7lEiHtHEWRCuesQ",
	"9yJQhZTcRRiTKXAFWCjCacjLCo1QO9CE515FU4dwuomg6THXoiz1pqMrYck9nqIlV3TnK9iyiTbep3GJ",
	"rTt7gJHO3JdbboSDcaVVqpWrjSDMvJcSgSUj1NQByIQahsM1Pm4MX7hDS9zQgBM2AX5xRyzlhCtAVRLu",
	"7+/vD66vDwYDVnKrBhL63f7RQbd30DuGqMY9TjXmVfC2mFcmq46rWbM3mWhzrWxLRCO0hfRJ95m1LJdc",
	"KYcj2iLtumirvP5qcAIx/NJZ92+nbN6O93vr7jgsmzluj7AthktjtGk2UKLTlli8MfNnEaBy9HuA4c1f",
	"51fDwbfhze3XO4hgeHN3Obo5v/p2ORp9HtWc1tiB1vJpi4M/CikZei+VzVvVK9FU5m0xfkK6EC6y3VWq",
	"GiPxdivuzYSitlIFs72f+Xd66mdLXCNKS5035P81vtUnhRM1JC5kSw7O01QE2WSlDeOPuiBGM2FDKoLm",
	"bPTvn8KSNiLhklnh2oQ0mwsryLV+mawdSrvOEKr0TmRoiWd5E9hXJZ4ZVeer4qBKg94KG3A5j61V6512",
	"j0/6/aNutyYxQtHJEbSJsOJZC9NueIaVvteS0alJ8kZiytgbsXqxen+0/to74u2fnpztFe8WH33wDZRb",
	"JWqy1T0j1ES30Op26INInOgKNWVk+BxlpaqPC2ZzTMRk4c5CN0R+kNiIcZWuZqtbL0SCpQqEGgFEUBgJ",
	"McyI8rjTkTrhcqYtxWdnZ2e++QT5cty5aXRh+JNEw85vhxDBHI0NGHuH3cOus9Y5Kp4LiOHDYffwg9MP",
	"TjPfLJ15r7OWjylSM9RPSIzPuXBkp1JLwD8aQhimweiiOjGlrvkn+91u6GxFGFqe57kUib/a+W6di5d1",
	"kddi1hCla20T/QRjxzYvAm9JRFNofUHbNbKKEKsIlxEc74V9PzBhsrUAGCpC4+TJopmjCfPGE9gWWcbN",
	"oizBKvHEpz49X8jjsDB2xq6QgXxheNuWSoYNwTLOFD5tMJY9CZqVlBWYVltYnaks54ZnSGia1a+tHhAa",
	"Dy191OnifaVv7MluuW2sq6frhfKVwVXb6urb2N7kadnrl5uq4lR/+U/ZvorkZT3CYLAxqFyITigX23q1",
	"MQFK6SjzsS3Ha+1cRrs9+SzudHXS75/2a66qnLf5CqiW459L9+5u9QZBdDFltkgStHZSSOk3+aP/ol8/",
	"8pSVDGcHTKg5lyJlQuUF1Vvk/yQfIbktbV9Tk1HQjrF3Ed6qaLkhl24UsRTnKHWeoaLS71sja7zytP3i",
	"50pJLDMofV1Jl6oUpqtWXogyrvgUnU+o0d2jXo6XfwcAAP//f3pW9VUQAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
