// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	INTERNALERROR ErrorCode = "INTERNAL_ERROR"
	INVALIDINPUT  ErrorCode = "INVALID_INPUT"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case INTERNALERROR:
		return true
	case INVALIDINPUT:
		return true
	default:
		return false
	}
}

// Coordinates defines model for Coordinates.
type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// CreateRouteRequest defines model for CreateRouteRequest.
type CreateRouteRequest struct {
	// DurationMaxDays Maximum duration of the trip in days (optional)
	DurationMaxDays *int `json:"durationMaxDays,omitempty"`

	// DurationMinDays Minimum duration of the trip in days
	DurationMinDays int `json:"durationMinDays"`

	// Points List of destination points for the route
	Points []string `json:"points"`

	// StartDate Start date for the trip in YYYY-MM-DD format
	StartDate openapi_types.Date `json:"startDate"`
}

// CreateRouteResponse Result of routes planning
type CreateRouteResponse struct {
	Points []RoutePoint `json:"points"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code ErrorCode `json:"code"`

	// Message Full error message
	Message string `json:"message"`
}

// ErrorCode Error code
type ErrorCode string

// RoutePoint defines model for RoutePoint.
type RoutePoint struct {
	Coordinates *Coordinates `json:"coordinates,omitempty"`

	// Details Additional details about this route point
	Details *string `json:"details,omitempty"`

	// EndTimestamp Unix timestamp for the end of this point in the route
	EndTimestamp int64 `json:"endTimestamp"`

	// Name Name of the route point/destination
	Name string `json:"name"`

	// StartTimestamp Unix timestamp for the start of this point in the route
	StartTimestamp int64 `json:"startTimestamp"`
}

// CreateRouteJSONRequestBody defines body for CreateRoute for application/json ContentType.
type CreateRouteJSONRequestBody = CreateRouteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new travel route
	// (POST /v1/routes)
	CreateRoute(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create a new travel route
// (POST /v1/routes)
func (_ Unimplemented) CreateRoute(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateRoute operation middleware
func (siw *ServerInterfaceWrapper) CreateRoute(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/routes", wrapper.CreateRoute)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWW2/jNhP9KwS/76EFlPiy2STQW3adogaSbOBmCwRBsJiIY5sLitSSIydG4P9ekJRs",
	"yVJufeibLV7mzMw5Z/jMM5MXRqMmx9Nn7rIl5hB+fjXGCqmBMPwtrCnQkoz/FJCkUqD/PTc2B+IpF6Z8",
	"UMgTTusCecp1mT+g5ZuEK6MX79+/SbjFX6W0KHh61zic7OLeb0+Zh5+YkY/y1SIQzkxJOMNfJTrqAhel",
	"BZJGX8LTBNbxE7rMysJ/5Sm/hCeZlzmrNzIzZ7RERlYWTGomYO3YbyZsB/U7Tzg+QV4o5OnoKOG51P44",
	"T0cJ16VS4DNMyZa4BSw14SLWZYtG6hfQxOteRdOEcNJG0I1YGFm1uh3oQjrylwt05JvuY8W9bG5siGl9",
	"YZvB7vjM5P7LNVjpYVwYLYz2vZGEeYhSIXBkpV54ALnU07i4wwfWwtovOgJLEyDsAvzLLzEBhFtAdRFu",
	"b29vDy4vDyYTVnGrAZKPh+Ojg+HoYPSZJw3uATWYV8PbY15VrCaubs/eZKIrjHY9Gc3QlSoUPVTWsUKB",
	"1h5HskfaXdO2df2/xTlP+f8GO/0OKvEOQtxrf8Zjade4P8O+HM6tNbYroMyInlzCZhbWEo7a0++OT6/+",
	"PruYTn5Mr66/3/CET69uzmdXZxc/zmezb7NG0AY70DlY9AT4o1SKYYhS73mrexWaentfjo1K9STa8r/X",
	"Ct60Sq9qJJCqR2RnQsjoG6zaw+DBlMRoKV1kQRRdi8B/SkfGygwUc9LzhAxbSSfJc79S4AtWsyssanEj",
	"c3QEedEF9l3LJ0b1+lZgqEU0HOkiLh+x1wpGJ8PPx+Px0XDY0JjUdHzE+1xIQ97T4yvIsTa4RjEGDU9q",
	"FabKvZNrUOvHsw3HPpDv+OT49F357vEyJN9BudeiLlv9NVLPTQ+trqchicy7jtQLRhZWqGpbeVgzV2Am",
	"52u/FhWfBCd1CQMttsPFz1eZYWVWsUecJ7y0iqd8SVSkg4EyGailcZSenp6eBoORFNpx4+34q4VHhZad",
	"XU95wldoXcQ4OhweDv1uU6CGQvKUfzocHn7yXge0DGIZrEaDiDmaXpzf7VyjszoGTONjK1H2KGlZZSpR",
	"1NOrmSArwEKOhNabuhd7+DwV24tnVaNtfD98MWIdvUATRpOAolAyC+cGP53H9LyjRc/7wj8KOmP+ZDeI",
	"XxmijWnYnGKe4cF43rSl7nto0yajN4vwIc6oUPfxcPixlLeZPO+cj09a/uZT9Ppa79O8ZRwV46p67Kt4",
	"J7lN8nKkUMUXQx2PxyfjRqi65n2xIqrN/b8rdzX0Q733xn4ga9AqCubKLEPn5qVS4QV09K7qvw9QnOA9",
	"EL6AYBXD2QGTegVKCiZ1UVJTIpuEf/4v4Ew1ofVD0aFdoY1jPtimK/Mc7Horzx7Ze7+FRSWk4B33IUS8",
	"q6Zl66nrHYwJXKEyRY6aqrhvOd39NtL+jd9qJ3HMogp9JVO5UjRlo4MR5aBhgT4mb9A9oN7cb/4JAAD/",
	"/4gI52mNDQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
